import { Injectable } from '@angular/core';
import {
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faBars,
    faBell,
    faCalendar,
    faCamera,
    faChartLine,
    faCheck,
    faChevronDown,
    faChevronRight,
    faCircle,
    faCircleCheck,
    faCircleNotch,
    faClock,
    faClose,
    faDotCircle,
    faEdit,
    faEnvelope,
    faExclamationCircle,
    faEye,
    faEyeSlash,
    faFileExcel,
    faFilePdf,
    faGear,
    faHammer,
    faHome,
    faImage,
    faInfo,
    faKey,
    faLayerGroup,
    faList,
    faLocation,
    faLock,
    faMinus,
    faOutdent,
    faPlus,
    faQuestionCircle,
    faSave,
    faSearch,
    faSignOutAlt,
    faStar,
    faTasks,
    faTrash,
    faUpload,
    faUser,
    faUsers,
    faUsersGear,
    faWarning,
    IconDefinition,
} from '@fortawesome/free-solid-svg-icons';

@Injectable({
    providedIn: 'root',
})
export class IconService {
    icons: { [key: string]: IconDefinition } = {
        close: faClose,
        edit: faEdit,
        delete: faTrash,
        eye: faEye,
        'eye-slash': faEyeSlash,
        plus: faPlus,
        check: faCheck,
        circle: faCircle,
        'dot-circle': faDotCircle,
        search: faSearch,
        save: faSave,
        loading: faCircleNotch,
        bars: faBars,
        home: faHome,
        'chevron-right': faChevronRight,
        star: faStar,
        list: faList,
        outdent: faOutdent,
        bell: faBell,
        hammer: faHammer,
        'users-gear': faUsersGear,
        'chart-line': faChartLine,
        calendar: faCalendar,
        user: faUser,
        'arrow-down': faArrowDown,
        'arrow-up': faArrowUp,
        minus: faMinus,
        'circle-notch': faCircleNotch,
        envelope: faEnvelope,
        'circle-check': faCircleCheck,
        lock: faLock,
        'arrow-right': faArrowRight,
        'arrow-left': faArrowLeft,
        'chevron-down': faChevronDown,
        gear: faGear,
        'question-circle': faQuestionCircle,
        'sign-out-alt': faSignOutAlt,
        'layer-group': faLayerGroup,
        'users': faUsers,
        location: faLocation,
        info: faInfo,
        upload: faUpload,
        key: faKey,
        chart: faChartLine,
        pdf: faFilePdf,
        excel: faFileExcel,
        tasks: faTasks,
        clock: faClock,
        image: faImage,
        warning: faWarning,
        trash: faTrash,
        camera: faCamera
    };

    getIcon(name: string): IconDefinition {
        return this.icons[name] || faCircle;
    }
}
